
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENER=PLAINTEXT://kafka:9093
      - KAFKA_LISTENER=PLAINTEXT://kafka:9093
      - KAFKA_LISTENER_PORT=9093
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafka-network
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    networks:
      - kafka-network
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - kafka-network
  spark-streaming:
    build:
      context: ./spark-streaming
    container_name: spark-streaming
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - KAFKA_BROKER=kafka:9093
    depends_on:
      - kafka
      - spark-master
    networks:
      - kafka-network
networks:
  kafka-network:
    driver: bridge
